### ISSUE TITLE
How to run pipenv with this python script

### ISSUE THREAD

**Issue by slidenerd** [ivarprudnikov/use-python-in-node#1]
Landed here straight from your post, fantastic effort, I am facing the same problem now, I need to run data analytical operations on live data using pandas and numpy, however it needs to be served on a frontend webapp, so far I am breaking my head over how to send data from Node to Python and landed on a few choices

- Redis pubsub
- Python shell
- Child process
- Websocket connection with ws in node and tornado in python
With your approach, if I had to say import numpy, pandas but they are installed with pipenv install numpy, how do I use it, any suggestions would be appreciated. Also what do you think is a decent approach to manage the whole node python data sending and receiving problem

**Comment by ivarprudnikov** [comment]
> I need to run data analytical operations on live data using pandas and numpy

It depends on how much data you need to analyze but putting it to some database would be preferable as then you effectively decouple data capture and analysis.

> if I had to say import numpy, pandas but they are installed with pipenv install numpy, how do I use it

In my example I assumed that everything is available in the `PATH`. I have not used `pipenv` yet but it looks like its a combo of `pip` and `virtualenv`. So you install packages with `pipenv` and then call Python script using different command in Node (https://docs.pipenv.org/en/latest/install/#using-installed-packages), eg:
```
spawn('pipenv', [
    "run", "python", "-u", SCRIPT_PATH, "--foo", param
])
```

Above example is not tested
